### ISSUE TITLE
Action.payload.error not getting set on failed request

### ISSUE THREAD

**Issue by chawes13** [LaunchPadLab/lp-redux-api#119]
Error object is getting assigned to action.payload.data which does not align with documentation

cc: @dpikt

**Comment by dpikt** [comment]
Two options here: change the docs to reflect the current behavior, or change the behavior to reflect the docs. 

@chawes13 what do you think your preferred behavior would be? Key under `data` or `error`?

**Comment by dpikt** [comment]
Sounds legit!
