### ISSUE TITLE
On success, middleware should dispatch data to client reducer BEFORE dispatching internal success

### ISSUE THREAD

**Issue by davemcorwin** [LaunchPadLab/lp-redux-api#20]
Otherwise, a component may attempt to rerender on success, but the data is not in the reducer yet.

**Comment by dpikt** [comment]
@davemcorwin should this behavior be the same for request and failure actions as well?

**Comment by davemcorwin** [comment]
i would think so




*Dave Corwin*
LaunchPad Lab <http://launchpadlab.com/> - Developer
*We Build Apps That Grow Your Business*

tele: 773-405-8401  |  twitter: @davidmcorwin

On April 5, 2017 at 3:12:28 PM, David Pickart (notifications@github.com)
wrote:

@davemcorwin <https://github.com/davemcorwin> should this behavior be the
same for request and failure actions as well?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/LaunchPadLab/lp-redux-api/issues/20#issuecomment-291982729>,
or mute the thread
